export default defineAppConfig({
  pages: [
    'pages/index/index',
    'pages/kitchen/index',
    'pages/discover/index',
    'pages/mine/index',
    'pages/login/index',
    'pages/recipe-detail/index',
    'pages/favorites/index',
    'pages/preferences/index',
    'pages/qa-history/index',
    'pages/profile-edit/index',
    'pages/agreement/index',
    'pages/privacy/index',
    'pages/onboarding/index',
    'pages/share-card/index',
    'pages/post-create/index',
    'pages/post-detail/index',
    'pages/post-share-card/index',
    'pages/comments/index',
    'pages/meal-plan/index',
    'pages/photo-capture/index',
    'pages/shopping-list/index',
    'pages/topic-square/index',
    'pages/user-profile/index',
    'pages/follow-list/index',
    'pages/seasonal-calendar/index',
    'pages/dark-rescue/index',
    'pages/family-vote/index',
    'pages/cooking-challenge/index',
    'pages/multi-agent/index',
    'pages/recipe-tree/index',
    'pages/voice-input/index',
    'pages/fridge/index',
  ],
  // 微信「同声传译」插件（语音输入 ASR）：需先在 mp.weixin.qq.com 后台
  // 设置→第三方设置→插件管理 搜索添加；version 以后台「插件详情」显示为准
  plugins: {
    WechatSI: {
      version: '0.3.5',
      provider: 'wx069ba97219f66d99',
    },
  },
  window: {
    // 所有页面都用自定义漫画风导航，隐藏微信原生导航栏（避免重复 title）
    navigationStyle: 'custom',
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#FFF7EC',
    navigationBarTitleText: 'ChefPal',
    navigationBarTextStyle: 'black',
    backgroundColor: '#FFF7EC',
  },
  tabBar: {
    custom: true,
    color: '#8A6F5C',
    selectedColor: '#E8482A',
    backgroundColor: '#FFFFFF',
    borderStyle: 'black',
    list: [
      { pagePath: 'pages/index/index', text: '百科' },
      { pagePath: 'pages/kitchen/index', text: '厨房' },
      { pagePath: 'pages/discover/index', text: '发现' },
      { pagePath: 'pages/mine/index', text: '我的' },
    ],
  },
  // 本地开发不校验域名
  permission: {},
})
