"""my_recipes restructure: servings/seasonings/prep_cook_steps, drop steps

Revision ID: 99f113b78b24
Revises: aede0027aa61
Create Date: 2026-08-11 16:26:44.528230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '99f113b78b24'
down_revision: Union[str, None] = 'aede0027aa61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('my_recipes', sa.Column('servings', sa.Integer(), nullable=False))
    op.add_column('my_recipes', sa.Column('prep_steps', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False))
    op.add_column('my_recipes', sa.Column('cook_steps', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False))
    op.add_column('my_recipes', sa.Column('seasonings', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False))
    op.drop_column('my_recipes', 'steps')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('my_recipes', sa.Column('steps', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('my_recipes', 'seasonings')
    op.drop_column('my_recipes', 'cook_steps')
    op.drop_column('my_recipes', 'prep_steps')
    op.drop_column('my_recipes', 'servings')
    # ### end Alembic commands ###
